# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c467ee6708ec7fa9b09a2ec2da610af861400e6fa783b8c636627e4d26ffcfc2fba498c2698cfef7821d9a1a6cb17637480fa0acd9f3de615b47e5454957ac34

test:
  secret_key_base: e9464ae2f4d1a024e2b4844164793c56b4ae03a1ceef7c29b7e89cc81b1fe8c9402ea267755b520e564414a199b79f7cafc6d4b10fcf221dc696f6073fae83f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
